name: CI/CD Solution Management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-bicep-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Bicep linter
        run: az bicep lint --file ./bicep/entry-point.bicep

  validate-bicep-files:
    needs: lint-bicep-files
    environment: devl
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_DEPLOYMENT_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_DEPLOYMENT_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}

      - name: Build bicep param file
        run: az bicep build-params --file ./bicep/.parameters/entry-point.devl.uksouth.bicepparam

      - name: Validate Deployment
        id: validate-deployment
        run: |
          validationResults=$(az deployment sub validate --name beus-main-val-${{ github.run_number }}-${{ github.run_attempt }} --location uksouth --template-file ./bicep/entry-point.bicep --parameters @./bicep/.parameters/entry-point.devl.uksouth.json | base64)
          echo "validationResults=$validationResults" >> "$GITHUB_OUTPUT"

      - name: Write Validation Deployment Output to Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.createReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.number }},
              body: $validationResults
            });

      - name: Perform What-If Deployment
        id: perform-whatif-deployment
        run: |
          whatIfResults=$(az deployment sub what-if --name beus-main-pln-${{ github.run_number }}-${{ github.run_attempt }} --location uksouth --template-file ./bicep/entry-point.bicep --parameters @./bicep/.parameters/entry-point.devl.uksouth.json)

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [ validate-bicep-files ]
    environment: devl
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_DEPLOYMENT_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_DEPLOYMENT_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        run: az stack sub create --name BEUS --description 'Blazor Server Experiments for US' --location uksouth --deny-settings-mode denyWriteAndDelete --action-on-unmanage deleteAll --template-file ./bicep/entry-point.bicep --parameters @./bicep/.parameters/entry-point.devl.uksouth.bicepparam