name: CI/CD Solution Management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-bicep-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Bicep linter
        run: az bicep lint --file ./bicep/entry-point.bicep

  validate-bicep-files:
    needs: lint-bicep-files
    environment: devl
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_DEPLOYMENT_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_DEPLOYMENT_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [ validate-bicep-files, build-and-test ]
    environment: devl
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_DEPLOYMENT_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_DEPLOYMENT_APP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure
        run: |
          az stack sub create --name BEUS --description 'Blazor Server Experiments for US' --location uksouth --deny-settings-mode denyWriteAndDelete --action-on-unmanage detachAll --template-file ./bicep/entry-point.bicep --parameters ./bicep/.parameters/entry-point.devl.uksouth.bicepparam |& tee ./stack-create.json
          [ $PIPESTATUS -eq 0 ] || exit $PIPESTATUS
      
      - name: Debugging
        run: cat ./stack-create.json